Repository fga-eps-mds/2023-1-schedula-detalhador-de-chamados, pull requests merged in 2023-06, with the labels that each got.

#5 #113 categorias tipos problema usuario externo
  package.json
  src/problem-category/dto/create-problem-category.dto.ts
  src/problem-category/dto/update-problem-category.dto.ts
  src/problem-category/entities/problem-category.entity.ts
  src/problem-category/problem-category.controller.spec.ts
  src/problem-category/problem-category.service.spec.ts
  src/problem-types/dto/createProblem-type.dto.ts
  src/problem-types/dto/updateProblem-type.dto.ts
  src/problem-types/entities/problem-type.entity.ts
  src/problem-types/problem-types.controller.spec.ts
  src/problem-types/problem-types.service.spec.ts
  yarn.lock
Labels: enhancement

#6 #101 Campos description e dateTime de Agendamentos agora podem ser editados
  src/schedules/schedules.service.ts
Labels: bug

#7 Sonar: deleting sonar files
  sonar-project.properties
Labels: documentation

#9 #33 endpoint homologacao
  src/issue-open/dto/createIssueOpendto.ts
  src/issue-open/dto/sendMailIssueOpendto.ts
  src/issue-open/dto/updateIssueOpendto.ts
  src/issue-open/entities/alertIssueOpen.entity.ts
  src/issue-open/entities/issueOpen.entity.ts
  src/issue-open/issueOpen.controller.spec.ts
  src/issue-open/issueOpen.controller.ts
  src/issue-open/issueOpen.module.ts
  src/issue-open/issueOpen.service.ts
  src/problem-category/problem-category.service.spec.ts
  src/schedules-open/schedulesOpen.module.ts
  src/schedules-open/schedulesOpen.service.spec.ts
  src/schedules-open/schedulesOpen.service.ts
  src/schedules/schedules.service.ts
Labels: enhancement
